### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jpleite** [foxhunt72/fhs-m3u2strm#2]
Hi,

Did install pip3 install fhs_m3u2strm. When listing groups with fhs-m3u2strm list-groups-details --m3ufile <path_to_local_file> [--vod-only] it works just fine. However, the command fhs-m3u2strm vod-group-to-dir --m3ufile <path_to_local_file> --group 'GROUPNAME'' --output-dir 'OUTPUT_DIR' is not working for me. It does not give any error but no files are created either. Any ideas? Thanks for your script

**Comment by BaQs** [comment]
Hello,

After reading the code, it seems the tool is broken when the m3u group is NOT composed by tv-series/episodes.
It checks an unreferenced attribute from the yaml file: "type".

So, try to add:
```type: movies```
to your group.

For instance:

Example yaml file.
---
```
config:
  season_folders: true
  square_brackets: true
  m3ufile: path to m3ufile   (optional also posible by argument)
  base_dir: base directory   (optional also posible by argument)
groups:
  - group: 'MOVIES'
    output_dir: "{PATH}/group1"
    rm_in_name:  "GRP "
    rm_end_name: " STAGE"
    type: movies

```

anything which is not 'episodes' will do
